name: Test app with Docker on Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t test-app-image .

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 test-app-image

      - name: Wait for App to Start
        run: sleep 10 

      - name: Test App
        run: | 
          curl -I http://localhost:8080 
          if [ $? -ne 0 ]; then
              exit 1
          fi
          
      - name: Stop Docker Container
        run: docker stop $(docker ps -q --filter ancestor=test-app-image)